<?php

namespace MenuBundle\Repository;

use Doctrine\ORM\EntityRepository;
use MenuBundle\Entity\Menu;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{

    /**
     * @param $name
     * @return Menu|null
     */
    public function findOneByName($name)
    {
        return $this->getRepository('MenuBundle:Menu')
            ->createQueryBuilder('o')
            ->select('o')
            ->where('o.name = :name')
            ->setParameter('name', $name)
            ->setMaxResults(1)
            ->getQuery()
            ->setCacheable($this->isCacheEnabled())
            ->getOneOrNullResult();

    }

    /**
     * @param $name
     * @return EntityRepository
     */
    protected function getRepository($name)
    {
        return $this->getEntityManager()->getRepository($name);
    }

    /**
     * @return bool
     */
    protected function isCacheEnabled()
    {
        if (class_exists('\Constants')) {
            return \Constants::$USE_DATABASE_CACHE;
        }
        return false;
    }

    /**
     * @return bool
     */
    protected function getCacheLifetime()
    {
        if (class_exists('\Constants')) {
            return \Constants::$DATABASE_CACHE_LIFETIME;
        }
        return 1;
    }
}
